#General Properties
groupId: '@project.groupId@'
artifactId: '@project.artifactId@'
version: '@project.version@'

# Don't run the Spring Boot web server
spring.main.web-application-type: servlet

# Unused feature
spring.groovy.template.check-template-location: false

# Geometry JSON output mode (GEOJSON_ONLY or WKT)
geometry.output.mode: GEOJSON_ONLY

# Kafka properties
spring.kafka.bootstrap-servers: localhost:9092

# Custom kafka properties
kafka.topics:
  autoCreateTopics: true
  numPartitions: 1
  numReplicas: 1
  createTopics:
    - name: topic.ProcessedSpat
      cleanupPolicy: delete
      retentionMs: 300000
    - name: topic.ProcessedMap
      cleanupPolicy: delete
      retentionMs: 300000
    - name: topic.ProcessedMapWKT
      cleanupPolicy: delete
      retentionMs: 300000
    - name: topic.ProcessedPsm
      cleanupPolicy: delete
      retentionMs: 300000
    - name: topic.ProcessedRtcm
      cleanupPolicy: delete
      retentionMs: 300000
    - name: topic.ProcessedSrm
      cleanupPolicy: delete
      retentionMs: 300000
    - name: topic.ProcessedSsm
      cleanupPolicy: delete
      retentionMs: 300000

# Jackson Properties
spring.jackson.serialization.write-dates-as-timestamps: false

kafka.linger_ms: 50

# Whether to fully decode RTCM payloads
# true = fully decode using the native gpsdecode tool
# false = partial decode: message type and station id only
rtcm.full.decode: true

geojsonconverter:
  kafka-topic-ode-rtcm-json: topic.OdeRtcmJson
  kafka-topic-processed-rtcm: topic.ProcessedRtcm
  kafka-topic-ode-srm-json: topic.OdeSrmJson
  kafka-topic-processed-srm: topic.ProcessedSrm
  kafka-topic-ode-ssm-json: topic.OdeSsmJson
  kafka-topic-processed-ssm: topic.ProcessedSsm
  # Replication factor
  # https://kafka.apache.org/11/streams/developer-guide/config-streams/#replicationfactor
  # -1 = broker default, 1 is default, 3 recommended for prod
  streams-config-replication-factor: ${GJC_STREAMS_CONFIG_REPLICATION_FACTOR:1}
  # Acks
  # https://kafka.apache.org/11/streams/developer-guide/config-streams/#recommended-configuration-parameters-for-resiliency
  # 1 default, all recommended for robustness in prod
  # May use 0 or 1 for dev
  streams-config-acks: ${GJC_STREAMS_CONFIG_ACKS:1}
  # Default 10 threads to match Connect default
  streams-config-num-stream-threads: ${GJC_STREAMS_CONFIG_NUM_STREAM_THREADS:10}
  streams-config-cache-max-bytes-buffering: ${GJC_STREAMS_CONFIG_CACHE_MAX_BYTES_BUFFERING:1048576}
  streams-config-commit-interval-ms: ${GJC_COMMIT_INTERVAL_MS:100}